{% set winpthread_ver = '9.0.0.6454.b4445ee52-1' %}
{% set gcc_ver = '13.2.0-2' %}

package:
  name: m2w64-gcc-libs
  version: 20230914

source:
  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gcc-libs-{{ gcc_ver }}-any.pkg.tar.zst
      # archive since the package link above expires when new versions appear.
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-gcc-libs-{{ gcc_ver }}-any.pkg.tar.zst
    sha256: fbc4bea0ec1492bf38050c8ca4a5b39ed3924a435f9f00a0a310d7573a027711
    folder: binary-gcc

  - url:
      # archive them for license compliance
      - https://repo.msys2.org/mingw/sources/mingw-w64-gcc-{{ gcc_ver }}.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-gcc-{{ gcc_ver }}.src.tar.zst
    sha256: d0b3ea0e4b3c1ded083db932c4a9e9eb11508393a50d6cf4f0d60df9c6363955
    folder: src-gcc

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-gcc-libgfortran-{{ gcc_ver }}-any.pkg.tar.zst
      # archive since the package link above expires when new versions appear.
      - https://github.com/conda-forge/msys2-recipes/releases/download/20230914-ucrt64/mingw-w64-ucrt-x86_64-gcc-libgfortran-{{ gcc_ver }}-any.pkg.tar.zst
    sha256: 8a19a81300229ed7e53fea7b9dcc3dc998e9f8f615482c712993bdb4f7e579da
    folder: binary-gfortran

build:
  number: 0
  skip: True  # [not win]

outputs:  
  - name: libgcc
    version: {{ gcc_ver.replace("-", ".") }}
    files:
      - Library/bin/libgcc_s_seh-1.dll
      - Library/bin/libquadmath-0.dll
    requirements:
      host:
        - libwinpthread
      run:
        - {{ pin_compatible('libwinpthread', exact=True) }}
      run_constrained:
        - msys2-conda-epoch <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_BIN%\libgcc_s_seh-1.dll exit 1
        - if not exist %LIBRARY_BIN%\libquadmath-0.dll exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: GPL-3.0-or-later
      license_file: binary-gcc/ucrt64/share/licenses/gcc-libs/
      summary: MinGW-w64 gcc runtime libs for C

  - name: libgomp
    version: {{ gcc_ver.replace("-", ".") }}
    files:
      - Library/bin/libgomp-1.dll
    requirements:
      host:
        - libwinpthread
        - {{ pin_subpackage('libgcc', exact=True) }}
      run:
        - {{ pin_compatible('libwinpthread', exact=True) }}
        - {{ pin_subpackage('libgcc', exact=True) }}
      run_constrained:
        - msys2-conda-epoch <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_BIN%\libgomp-1.dll exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: GPL-3.0-or-later
      license_file: binary-gcc/ucrt64/share/licenses/gcc-libs/
      summary: MinGW-w64 gcc runtime libs for OpenMP

  - name: libstdcxx
    version: {{ gcc_ver.replace("-", ".") }}
    files:
      - Library/bin/libstdc++-6.dll
    requirements:
      host:
        - libwinpthread
        - {{ pin_subpackage('libgcc', exact=True) }}
      run:
        - {{ pin_compatible('libwinpthread', exact=True) }}
        - {{ pin_subpackage('libgcc', exact=True) }}
      run_constrained:
        - msys2-conda-epoch <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_BIN%\libstdc++-6.dll exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: GPL-3.0-or-later
      license_file: binary-gcc/ucrt64/share/licenses/gcc-libs/
      summary: MinGW-w64 gcc runtime libs for C++

  - name: libgfortran5
    version: {{ gcc_ver.replace("-", ".") }}
    files:
      - Library/bin/libgfortran-5.dll
    requirements:
      host:
        - libwinpthread
        - {{ pin_subpackage('libgcc', exact=True) }}
      run:
        - {{ pin_compatible('libwinpthread', exact=True) }}
        - {{ pin_subpackage('libgcc', exact=True) }}
      run_constrained:
        - msys2-conda-epoch <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_BIN%\libgfortran-5.dll exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: GPL-3.0-or-later
      license_file: binary-gcc/ucrt64/share/licenses/gcc-libs/
      summary: MinGW-w64 gcc runtime libs for Fortran

  - name: libgfortran
    version: {{ gcc_ver.replace("-", ".") }}
    requirements:
      run:
        - {{ pin_subpackage('libgfortran5', exact=True) }}
      run_constrained:
        - msys2-conda-epoch <0.0a0
    test:
      commands:
        - if not exist %LIBRARY_BIN%\libgfortran-5.dll exit 1
    about:
      home: https://mingw-w64.sourceforge.io/
      license: GPL-3.0-or-later
      license_file: binary-gcc/ucrt64/share/licenses/gcc-libs/
      summary: MinGW-w64 gcc runtime libs for Fortran

about:
  home: https://mingw-w64.sourceforge.io/
  license: GPL-3.0-or-later
  license_file: binary-gcc/ucrt64/share/licenses/gcc-libs/
  summary: |
    Repackaged MinGW-w64 gcc runtime libraries

extra:
  recipe-maintainers:
    - isuruf
